### PR TITLE
Updated syntax to match latest (1.0.0) flutter_bloc version

### LINKED ISSUE #5: Breaking changes in flutter_bloc and FB login dependencies
Recent dependency updates have broken the sample:
- flutter_bloc has deprecated dispatch in 1.0.0
- In flutter_facebook_login 3.0.0, loginWithReadPermission renamed to login

My solution in the short term is:
- pin flutter_bloc to 0.16.0 (later versions also contain breaking changes) in pubspec.yaml
- update call to logInWithReadPermission() with logIn() in login_bloc.dart

I am submitting a PR for this fix, but creating an issue as it may be better to update the code for the flutter_bloc  method change rather than pin the plugin version.

### PR DESCRIPTION
**Pull request by nstosic**
Fixes #5 and renders #6 obsolete.

It seems that only the syntax changes in `flutter_bloc` 1.0.0 and functionality stayed the same so it was easy for me to resolve the issues.

### CODE REVIEW

**Comment by cloudwheels** [comment]
@nstosic I'm afraid I can't get this to build - did you?

To begin I get the error noted in my PR re: gradle version & shared preferences.
```
A problem occurred evaluating root project 'shared_preferences'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /home/nigel/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+3/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip
```
My branch `cloudwheels:cloudwheels-fixes` will build successfully after making the update to 5.1.1 in gradle-wrapper.properties. With this branch however I get:

```
...
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':app:processDebugManifest'.                                                             
> Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.2] AndroidManifest.xml:22:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:15:5-59:19 to override.
...
```

If I make the suggested change to the manifest  (also adding the namespace declaration in the header for tools to avoid another error i.e. `xmlns:tools="http://schemas.android.com/tools"`) then I get the following error:
```
...
/home/nigel/toptal-fixes/android/app/src/main/AndroidManifest.xml:16:5-61:19 Error:
        tools:replace specified at line:16 for attribute android:appComponentFactory, but no new value specified
/home/nigel/toptal-fixes/android/app/src/main/AndroidManifest.xml Error:
        Validation failed, exiting                                      
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugManifest'.                  
> Manifest merger failed with multiple errors, see logs  
...
```

Unfortnately I am out of time to investigate further right now.

I am just about to update flutter version but current system is:
```
Flutter (Channel master, v1.10.15-pre.186, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.15-pre.186 at /home/nigel/flutter
    • Framework revision 1c535de7e0 (12 days ago), 2019-10-18 16:40:42 -0700
    • Engine revision 8aefcd8575
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)
```

**Comment by nstosic** [comment]
Yeah, I've built it and smoke-tested for iOS. I'll check Android and report back by Friday.

I'm using `flutter channel stable` though, I see you're on `master`. I'll update the README to reflect that the repo is built for `stable`.

**Comment by cloudwheels** [comment]
@nstosic OK I found it! The gradle.properties is somehow corrupted so`android.enableJetifier=true` is not on its own line (I had changed in my branch but thought I may have introduced this error so didn't add commit to PR).
So, I think you need to make the changes below (after this it builds on Android, smoketested ACK [even on master ;)]):
```
$ git diff origin/bugfix/flutter_bloc_breaking_change..HEAD
```
```diff
diff --git a/android/gradle.properties b/android/gradle.properties
index 4d3226a..a673820 100644
--- a/android/gradle.properties
+++ b/android/gradle.properties
@@ -1,3 +1,4 @@
 org.gradle.jvmargs=-Xmx1536M
 android.useAndroidX=true
-android.enableJetifier=true
\ No newline at end of file
+android.enableJetifier=true
+android.enableR8=true
diff --git a/android/gradle/wrapper/gradle-wrapper.properties b/android/gradle/wrapper/gradle-wrapper.properties
index 2819f02..9b6616c 100644
--- a/android/gradle/wrapper/gradle-wrapper.properties
+++ b/android/gradle/wrapper/gradle-wrapper.properties
@@ -3,4 +3,4 @@ distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
```

**Comment by nstosic** [comment]
Hey @cloudwheels I tried building it on Android, and was successful with the current state of the branch.

However, I also succeeded building it on `stable` channel after applying your proposed changes (in `gradle.properties` and `gradle-wrapper.properties`, so I'm pushing those changes to this branch.

Let me know if you can build it this time, and if the feedback is positive, I'll merge this PR.

**Comment by cloudwheels** [comment]
Hi @nstosic,

My comment above is a diff between this branch and my local copy of the
branch with these changes, which built successfully, i.e. already tested!

Interesting as to whether this error is introduced by something in Flutter
master or otherwise.

In the absence of further/more formal testing, however, for my part I would
say it's safe to merge this.

**Comment by nstosic** [comment]
Great, I'm merging this. Thanks for raising the issue and for testing it.

**Pull request merged**
